name: "Install boost"
description: "Build or retrieve boost & set paths"
inputs:
  version:
    description: "Version of boost to install"
    required: false
    default: 'latest'
  download-url:
    description: "Where to download the archive from"
    required: false
  variant:
    description: "Variants to build"
    required": false
    default: debug,release
  toolset:
    description: "Toolset to use"
    required: true
  runtime-link:
    description: "How to link the runtime library"
    required: false
    default: static,shared
  threading:
    description: "Threading mode to use"
    required: false
    default: multi,single
  link:
    description: "How to link boost"
    required: false
    default: static
  cxxstd:
    description: "C++ standard to use (restricts which libraries are built)"
    required: false
    default: static
  address-model:
    description: "Address-model"
    required: false
    default:
outputs:
  boostdir:
    description: "Path at which boost was installed"
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        BOOST_TAG="${{ inputs.version == 'latest' && '`gh release view -R boostorg/boost --jq ".name" --json name`' || format('boost-{0}', inputs.version) }}"
        echo BOOST_TAG="$BOOST_TAG" >> $GITHUB_ENV
        BOOST_KEY_RAW=$BOOST_TAG.${{ inputs.toolset }}.${{ inputs.variant }}.${{ inputs.link }}.${{ inputs.runtime-link }}.${{ inputs.threading }}.${{ inputs.cxxstd }}"
        echo BOOST_KEY=${BOOST_KEY_RAW//,/-} >> $GITHUB_ENV

    - name: Restore boost
      id: restore-boost
      uses: actions/cache/restore@v4
      with:
        path: '${{ github.workspace }}/boost-install'
        key: ${{ env.BOOST_KEY }}

    - name: Add MSBuild to PATH
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2

    - name: Download Boost source
      id: checkout-boost
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        archive='${{ env.BOOST_TAG }}' &&
        gh release download ${{ env.BOOST_TAG }} -R boostorg/boost -p 'boost-*-b2-nodocs.7z' -O "$archive".7z --clobber &&
        7z x "$archive".7z -spe &&
        mv $archive boost

    - name: Build boost
      shell: bash
      run: |
        mkdir boost-install
        (cd boost && ./bootstrap.sh && ./b2 install --prefix="../boost-install" -q toolset=${{ inputs.toolset }} variant=${{ inputs.variant }} cxxstd=${{ inputs.cxxstd }} runtime-link=${{ inputs.runtime-link }} ${{ inputs.address-model != '' && format('address-model={0}', inputs.address-model) || '' }} threading=${{ inputs.threading }} link=${{ inputs.link }})

    - name: Cache boost
      id: cache-boost
      uses: actions/cache/save@v4
      with:
        path: 'boost-install'
        key: ${{ steps.restore-boost.outputs.cache-primary-key }}