name: Windows Build
on:
  push:

permissions: read-all

jobs:
  linux-ci:
    name: Linux Test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.codename }}-${{ matrix.os.arch }}-(${{ matrix.cfg.cxx }}-${{ matrix.cfg.version }}-${{ matrix.build-type }})
      cancel-in-progress: true
    runs-on: ${{ matrix.os.dist }}-${{ matrix.os.version }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64 ]
        os:
          - { name: 'Ubuntu', dist: 'ubuntu', version: 24.04 }
        variant: [ debug, release ]
        toolset: [ clang, gcc ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/action.yml
        with:
          toolset: ${{ matrix.toolset }}
          variant: ${{ matrix.variant }}

  windows-ci:
    name: Windows Test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os.dist }}-${{ matrix.os.arch }}-(${{ matrix.cfg.version }}-${{ matrix.cfg.generator }}-${{ matrix.build-type }})
      cancel-in-progress: true
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        arch: [ x64 ]
        os:
          - { name: 'Windows', dist: windows, version: 2022 }
        variant: [ debug, release ]
        toolset: [ msvc ]
    runs-on: ${{ matrix.os.dist }}-${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: ./.github/action.yml
        with:
          toolset: ${{ matrix.toolset }}
          variant: ${{ matrix.variant }}
